#include "test_support.h"

namespace prob_livo_test {

int RunSo3GoldenTests(TestContext &context) {
  // Golden values were generated by the actual Super implementation at
  // reference commit 9fc949f46291c0fa76e5b7cdb372c940eb4b3f6e:
  // src/basic/src/Manifold.cpp, BASIC::SO3::Exp/log_vee.  The generator was
  // compiled against src/basic/include and that exact source; this fixture is
  // intentionally independent of the production helper.
  struct Fixture {
    Eigen::Vector3d phi;
    Eigen::Matrix3d rotation;
    Eigen::Vector3d logarithm;
  };
  const std::vector<Fixture> fixtures = {
      {Eigen::Vector3d(1.0e-10, -2.0e-10, 3.0e-10),
       (Eigen::Matrix3d() << 1.0, -2.999999971e-10, -2.000000027e-10,
        2.999999971e-10, 1.0, -1.000000013e-10, 2.000000027e-10,
        1.000000013e-10, 1.0)
           .finished(),
       Eigen::Vector3d(1.000000013e-10, -2.000000027e-10,
                       2.999999971e-10)},
      {Eigen::Vector3d(0.001, -0.002, 0.0015),
       (Eigen::Matrix3d() << 0.999996841, -0.001501001185, -0.001999245491,
        0.001498995116, 0.9999983907, -0.001001503435, 0.002000750042,
        0.0009984943317, 0.9999974966)
           .finished(),
       Eigen::Vector3d(0.001000000047, -0.002000000095, 0.001500000013)},
      {Eigen::Vector3d(0.4, -0.3, 0.2),
       (Eigen::Matrix3d() << 0.9365557432, -0.249036476, -0.246666193,
        0.1319085807, 0.9023934603, -0.4102270305, 0.3247514367,
        0.3516630828, 0.8779917955)
           .finished(),
       Eigen::Vector3d(0.3999999762, -0.3000000119, 0.1999999881)},
      {Eigen::Vector3d(-1.1, 0.5, 0.3),
       (Eigen::Matrix3d() << 0.8508546948, -0.4695537686, 0.2357234657,
        -0.01297521591, 0.4297384024, 0.9028601646, -0.5252408981,
        -0.7712613344, 0.3595523834)
           .finished(),
       Eigen::Vector3d(-1.100000024, 0.5000000596, 0.2999999821)}};

  double max_rotation_error = 0.0;
  double max_log_error = 0.0;
  double max_roundtrip_error = 0.0;
  for (const Fixture &fixture : fixtures) {
    const Eigen::Matrix3d production_rotation =
        prob_livo::ExpSO3(fixture.phi);
    const Eigen::Vector3d production_log =
        prob_livo::LogSO3(production_rotation);
    const double rotation_error =
        (production_rotation - fixture.rotation).cwiseAbs().maxCoeff();
    const double log_error = (production_log - fixture.logarithm).norm();
    const double roundtrip_error = (production_log - fixture.phi).norm();
    max_rotation_error = std::max(max_rotation_error, rotation_error);
    max_log_error = std::max(max_log_error, log_error);
    max_roundtrip_error = std::max(max_roundtrip_error, roundtrip_error);
  }
  context.Record("so3.golden_rotation", max_rotation_error);
  context.Record("so3.golden_log", max_log_error);
  context.Record("so3.roundtrip", max_roundtrip_error);
  context.Check(max_rotation_error < 2e-7,
                "production ExpSO3 diverged from actual Super golden values");
  context.Check(max_log_error < 2e-7,
                "production LogSO3 diverged from actual Super golden values");
  context.Check(max_roundtrip_error < 2e-7,
                "production SO3 Log(Exp(phi)) left the operating range");

  // A common wrong port uses linear rotation interpolation.  Its result is
  // not a valid rotation for this nontrivial fixture and must stay distinct.
  const Eigen::Matrix3d linear_mutation =
      Eigen::Matrix3d::Identity() + prob_livo::HatSO3(fixtures[2].phi);
  context.Check((linear_mutation - fixtures[2].rotation).norm() > 1e-2,
                "linear SO3 mutation was not discriminated");
  return context.Passed() ? 0 : 1;
}

}  // namespace prob_livo_test
